<script setup lang="ts">
import { ref, computed } from "vue";
import type {
  Security,
  PrintTheme,
  PosterSize,
} from "~/pages/tools/wifi-qr.vue";

const props = defineProps<{
  qrSvg: string;
  ssid: string;
  security: Security;
  displayPassword: string;
  theme: PrintTheme;
  posterSize: PosterSize;
  shopName: string;
  tagline: string;
  showPassword: boolean;
  showDontShare: boolean;
  khmerHeadline: string;
  enHeadline: string;
}>();

const el = ref<HTMLElement | null>(null);

defineExpose({
  getEl: () => el.value,
});

const posterSizeClass = computed(() =>
  props.posterSize === "A4" ? "max-w-[520px]" : "max-w-[420px]"
);

const posterWrapClass = computed(() => {
  if (props.theme === "minimal") return "bg-white border border-gray-200";
  if (props.theme === "modern")
    return "bg-white border border-gray-200 shadow-sm";
  return "bg-white border border-gray-200";
});

const posterBarClass = computed(() => {
  if (props.theme === "minimal") return "bg-gray-100 text-gray-900";
  if (props.theme === "modern") return "bg-gray-900 text-white";
  return "bg-gray-900 text-white";
});
</script>

<template>
  <div :class="['mx-auto', posterSizeClass]">
    <div
      ref="el"
      :class="['print-card rounded-[24px] bg-white p-4', posterWrapClass]"
    >
      <div class="cutline rounded-[18px] p-4">
        <!-- Top bar -->
        <div :class="['rounded-2xl px-3 py-2 text-center', posterBarClass]">
          <p class="text-xs opacity-90">
            {{ props.shopName?.trim() || "Wi-Fi" }}
          </p>

          <p class="text-base font-bold leading-tight mt-1">
            {{ props.theme === "minimal" ? "Wi-Fi" : "Free Wi-Fi" }}
          </p>

          <p v-if="props.tagline?.trim()" class="text-[11px] opacity-90 mt-1">
            {{ props.tagline.trim() }}
          </p>
        </div>

        <!-- Headlines -->
        <div class="text-center mt-3 space-y-1">
          <p class="khmer text-sm font-bold text-gray-900">
            {{ props.khmerHeadline }}
          </p>
          <p class="text-[11px] text-gray-500">{{ props.enHeadline }}</p>
        </div>

        <!-- QR frame -->
        <div class="my-4 flex justify-center">
          <div class="qr-frame rounded-2xl border bg-white p-2">
            <div
              v-if="props.qrSvg"
              v-html="props.qrSvg"
              class="[&>svg]:w-[240px] [&>svg]:h-[240px]"
            ></div>

            <p v-else class="text-sm text-gray-500 p-4">
              Enter SSID to generate QR
            </p>
          </div>
        </div>

        <!-- Details -->
        <div class="space-y-2 text-sm">
          <div class="rowbox">
            <span class="label">Wi-Fi</span>
            <span class="value">{{ props.ssid || "—" }}</span>
          </div>

          <div
            v-if="props.security !== 'nopass' && props.showPassword"
            class="rowbox"
          >
            <span class="label">Password</span>
            <span class="value">{{ props.displayPassword || "—" }}</span>
          </div>

          <p
            v-if="props.security !== 'nopass' && !props.showPassword"
            class="text-[11px] text-gray-500 text-center"
          >
            Password required — please ask staff.
          </p>

          <p
            v-if="
              props.security !== 'nopass' &&
              props.showPassword &&
              props.showDontShare
            "
            class="khmer text-[11px] text-gray-500 text-center pt-1"
          >
            សូមកុំចែករំលែកពាក្យសម្ងាត់ជាមួយអ្នកដទៃ 🙏
          </p>
        </div>

        <div class="mt-4 text-center text-[11px] text-gray-400">
          Generated by ChlatWork • chlatwork.com
        </div>
      </div>
    </div>
  </div>
</template>

<style>
@font-face {
  font-family: "Hanuman";
  src: url("/assets/fonts/Hanuman-VariableFont_wght.ttf") format("truetype");
  font-weight: 100 900;
  font-style: normal;
  font-display: swap;
}

.khmer {
  font-family: "Hanuman", system-ui, -apple-system, Segoe UI, Roboto, Arial,
    sans-serif;
}

.cutline {
  border: 2px dashed rgba(0, 0, 0, 0.18);
  background: #fff;
}

.qr-frame {
  box-shadow: 0 6px 18px rgba(0, 0, 0, 0.06);
}

.rowbox {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  border: 1px solid rgba(0, 0, 0, 0.08);
  background: rgba(0, 0, 0, 0.02);
  border-radius: 14px;
  padding: 10px 12px;
}

.label {
  color: rgba(0, 0, 0, 0.55);
  font-size: 12px;
}

.value {
  font-weight: 700;
  color: rgba(0, 0, 0, 0.88);
  max-width: 60%;
  text-align: right;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* Print ONLY the poster */
@media print {
  @page {
    size: auto;
    margin: 12mm;
  }

  body * {
    visibility: hidden !important;
  }

  .print-card,
  .print-card * {
    visibility: visible !important;
  }

  .print-card {
    position: fixed;
    inset: 0;
    margin: auto;
    box-shadow: none !important;
    padding: 0 !important;
    max-width: 640px;
    width: 92vw;
    height: fit-content;
  }
}
</style>
