<script setup lang="ts">
useSeoMeta({
  title: "Terms of Service — ChlatWork",
  description: "Terms for using ChlatWork tools.",
});
</script>

<template>
  <main class="mx-auto w-full px-4 py-10 space-y-6">
    <header class="space-y-2">
      <h1 class="text-2xl font-bold">Terms of Service</h1>
      <p class="text-gray-600">
        By using ChlatWork, you agree to the terms below.
      </p>
    </header>

    <section class="space-y-3">
      <h2 class="text-lg font-semibold">Use of the service</h2>
      <p class="text-gray-700">
        You may use ChlatWork tools for personal and business tasks as long as
        you do not misuse the service or attempt to break, abuse, or overload
        the system.
      </p>
      <ul class="list-disc pl-5 text-gray-700 space-y-1">
        <li>No illegal content or harmful activity.</li>
        <li>No attempts to bypass security or exploit vulnerabilities.</li>
        <li>No automated scraping that impacts performance.</li>
      </ul>
    </section>

    <section class="space-y-3">
      <h2 class="text-lg font-semibold">Tool outputs</h2>
      <p class="text-gray-700">
        Outputs generated by tools (barcodes, QR codes, conversions, etc.) are
        provided “as is”. You are responsible for verifying correctness before
        using them in production, printing, or business workflows.
      </p>
    </section>

    <section class="space-y-3">
      <h2 class="text-lg font-semibold">Availability</h2>
      <p class="text-gray-700">
        We may update, remove, or change tools at any time. We aim to keep the
        service stable but cannot guarantee uninterrupted availability.
      </p>
    </section>

    <section class="space-y-3">
      <h2 class="text-lg font-semibold">Advertising</h2>
      <p class="text-gray-700">
        ChlatWork may display ads from Google AdSense or other advertising
        partners. You must not click ads repeatedly, encourage others to click
        ads, use automated methods to generate ad impressions or clicks, or
        interact with ads in a way that violates advertising network policies.
      </p>
      <p class="text-gray-700">
        Advertising and cookie practices are described in our Privacy Policy and
        Cookie Policy.
      </p>
    </section>

    <section class="space-y-3">
      <h2 class="text-lg font-semibold">Disclaimer</h2>
      <p class="text-gray-700">
        ChlatWork is provided without warranties of any kind. To the maximum
        extent permitted by law, we are not liable for any damages or losses
        resulting from use of the tools.
      </p>
    </section>
  </main>
</template>
